{
 "title": "Spoticord",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "guild", "label": "Guild", "query": "total_listen_amount" },
   {
    "name": "TPI",
    "label": "Tracks per Interval",
    "query": "1m,5m,15m,30m,45m,1h,2h,5h,1d,1w"
   }
  ]
 },
 "panels": [
  {
   "title": "Discord Gateway Ping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "discord_ping_websocket" }
   ]
  },
  {
   "title": "Total Listen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_listen_amount {guild=~\"$guild\"}",
     "legendFormat": "Listencount: {{guild}}"
    }
   ]
  },
  {
   "title": "Total Tracks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_track_amount", "legendFormat": "Tracks" }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_artist_amount", "legendFormat": "Tracks" }
   ]
  },
  {
   "title": "Albums",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_album_amount", "legendFormat": "Tracks" }
   ]
  },
  {
   "title": "Discord Rest Ping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "discord_ping_rest" }
   ]
  },
  {
   "title": "Current Listen Members",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_listen_members {guild=~\"$guild\"}",
     "legendFormat": "Current listen: {{guild}}"
    }
   ]
  },
  {
   "title": "Guilds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_guilds" }
   ]
  },
  {
   "title": "Tracks per Interval ($TPI)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tracks_per_minute {guild=~\"$guild\"}[$TPI])",
     "legendFormat": "Tracks: {{guild}}"
    }
   ]
  },
  {
   "title": "Peak Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_peak_time {guild=~\"$guild\"} / 1000",
     "legendFormat": "Guild: {{guild}}"
    }
   ]
  }
 ]
}